Qrlg36 ces ach bon v2 creation zone question serious game
univ-angers/QRLudo-Generator pull request #123
Opened 2021-11-17 16:59 UTC by CesAchBon

2021-11-17 20:23 UTC, pdelepine reviewed
Petit changement à faire.
Sinon un `Ctrl` + `shift` + `i` pour formater correctement le code ne ferait pas de mal  ;)

2021-11-17 20:23 UTC, pdelepine commented on app/rendererProcess/model/SGNode.js
> +					this.emptyQuestionZone();
Faire un `emptyQuestionZone` ici empêche l'affichage de la zone d'un autre noeud si cet autre noeud est parcouru avant celui-ci

2021-11-17 20:23 UTC, pdelepine commented on app/rendererProcess/model/SGNode.js
> +		this.questionZone=myP5.createDiv('NOT YET IMPLEMENTED');
À changer du coup ?

2021-11-17 21:35 UTC, CesAchBon commented on app/rendererProcess/model/SGNode.js
> +					this.emptyQuestionZone();
Effectivement, en revancche il faut trouver où le placer pour gérer l'effacement de la zone quand on cliques sur le Canvas (en dehors d'un noeud)

2021-11-17 21:35 UTC, CesAchBon commented on app/rendererProcess/model/SGNode.js
> +		this.questionZone=myP5.createDiv('NOT YET IMPLEMENTED');
Oui, j'allais le changer avec l'ajout de la documentation :)

2021-11-17 22:07 UTC, CesAchBon commented on app/rendererProcess/model/SGNode.js
> +					this.emptyQuestionZone();
C'est corrigé je pusherai demain en meme temps que la documentation

2021-11-22 18:42 UTC, pdelepine requested changes
Globalement cela marche, 2 modifs à faire
Le css n'est pas bloquant alors on le changera plus tard

2021-11-22 18:42 UTC, pdelepine commented on app/rendererProcess/model/SGNode.js
> +			myP5.strokeWeight(6);
Un stroke de 10 serait plus visible

2021-11-22 18:42 UTC, pdelepine commented on app/rendererProcess/model/SGQuestionNode.js
> +			myP5.strokeWeight(6);
Pareil un stroke de 10 serait mieux

2021-11-22 18:42 UTC, pdelepine commented on app/rendererProcess/model/SGQuestionNode.js
> +
Un ajout auto a retirer

2021-11-22 18:42 UTC, pdelepine commented on app/rendererProcess/model/SGQuestionNode.js
> +		this.btn_add_answer.parent('displayQuestionZone');
Il n'y a pas besoin d'afficher un bouton d'ajout de réponse si on arrive a 5 réponses

2021-11-22 18:42 UTC, pdelepine commented on app/rendererProcess/model/SGQuestionNode.js
> +	}
Au final comme lorsqu'on ajoute une réponse ou en supprime on sauvegarde les modifs courante, il s'agit plus d'un discard des modifications des input text non sauvegarder

2021-11-22 18:42 UTC, pdelepine commented on app/rendererProcess/model/SGTextNode.js
> +			myP5.strokeWeight(6);
stooke de 10 serait mieux

2021-11-22 21:11 UTC, pdelepine approved these changes

2021-11-22 21:12 UTC, merged